/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ihm;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.GridLayout;

/**
 *
 * @author Johan
 */
public class Grille extends javax.swing.JPanel {
    public int nbLigne;
    public int nbColonne;
    private Dimension dimensionCase;
    public static Case casePanelTable[][];
    private MainFraime frame;
    
    final String red = "red";
    final String green = "green";
    final String blue = "blue";
    
    public Color greenColor = new Color(188, 255, 181);
    public Color redColor = new Color(255, 181, 181);
    public Color blueColor = new Color(181, 255, 255);
    
    
    /**
     * Creates new form Grille
     */
    public Grille(int lignes, int colonnes, MainFraime pere) {
        initComponents();
        nbLigne = lignes;
        nbColonne = colonnes;
        frame = pere;
        dimensionCase = calculTailleCase();
        
        setLayout(new GridLayout(lignes, colonnes, 0, 0));
        casePanelTable = new Case[nbLigne][nbColonne];
        for(int colonne = 0; colonne < nbColonne; colonne ++) {
            for(int ligne = 0; ligne < nbLigne; ligne ++) {
                casePanelTable[ligne][colonne] = new Case(dimensionCase, ligne, colonne, this);
                add(casePanelTable[ligne][colonne]);
            }
        }   
        setVisible(true);

    }
    private Dimension calculTailleCase() {
        return new Dimension(this.getWidth()/nbLigne, this.getHeight()/nbColonne);
    }

    public void addComposant(Case c, int id, Type type, Couleur couleur) {
        Composant composantToAdd = new Composant(id, type, couleur);
        c.addComposant(composantToAdd);
    }
    
    public void removeComposant(Case c, int id, Type type, Couleur couleur) {
        Composant composantToRemove = new Composant(id, type, couleur);
        c.removeComposant(composantToRemove);
    }

    public static Case[][] getCasePanelTable() {
        return casePanelTable;
    }
    
    
    
    public void updateInfos(int ligne, int colonne) {
        frame.getjLabelPositionX().setText(String.valueOf(ligne));
        frame.getjLabelPositionY().setText(String.valueOf(colonne));
        
        String infos = "<html>";
        Case c = casePanelTable[ligne][colonne];
        for (Composant composant : c.listComposants) {
            infos += composant.toString();
        }
        infos+="</html>";
        frame.getjLabelComposantsCase().setText(infos);
    }
    
    public void move(int idComposant, Type type, Couleur couleur, int oldAbs, int oldOrd, int abs, int ord) {
        Case cOld = casePanelTable[oldAbs][oldOrd];
        cOld.removeAll();
        Case cNew = casePanelTable[abs][ord];
        
        removeComposant(cOld, idComposant, type, couleur);
        addComposant(cNew, idComposant, type, couleur);
        //cNew.addComposant(toMove);
        validate();
    }
    
    public void clearGrille() {
        for (int i = 0; i < nbLigne; i++) {
            for (int j = 0; j < nbColonne; j++) {
                casePanelTable[i][j].clearCase();
                validate();
            }
            
        }
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
