/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package testihm;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JSlider;
import javax.swing.SwingConstants;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;

/**
 *
 * @author jdebat
 */
public class mainFraime extends javax.swing.JFrame {
    private Grille grille;
    private int ligne = 30;
    private int colonne = 30;
    private int robot = 10;
    private boolean isRunning = false;
    private XmlToPersist persister;
    /**
     * Creates new form mainFraime
     */
    public mainFraime() {
        initComponents();
        
        myInitComponents();
        
        pack();
    }

    private void myInitComponents() {
        
        Color first = new Color(107, 107, 107);
        Toolkit tk = Toolkit.getDefaultToolkit();  
        int xSize = ((int) tk.getScreenSize().getWidth());  
        int ySize = ((int) tk.getScreenSize().getHeight());
        
        // Taille frame
        int widthFrame = (int) (Math.round(xSize * 0.95));
        int heightFrame = (int) (Math.round(ySize * 0.95));
        this.setPreferredSize(new Dimension(widthFrame, heightFrame));
        this.setResizable(false);
        this.getContentPane().setBackground(first);
        
        // Taille grille
        grille = new Grille(ligne, colonne, this);
        grille.setSize(new Dimension((int) (Math.round(widthFrame * 0.60)), (int) (Math.round(heightFrame * 0.96))));
        grille.setBackground(first);
        this.add(grille, BorderLayout.CENTER);
        
        // Gestionnaire persistence
        persister = new XmlToPersist(grille);
        
        // Taille optionPanel
        optionsPanel.setPreferredSize(new Dimension((int) (Math.round(widthFrame * 0.38)), (int) (Math.round(heightFrame * 0.98))));
        optionsPanel.setBackground(first);
        
        // upadatePanel
        int widthUpdatePanel = updatePanel.getWidth();
        updatePanel.setPreferredSize(new Dimension(widthUpdatePanel, (int) (Math.round(heightFrame * 0.25))));
        updatePanel.setBackground(first);
        updatePanel.setBorder(BorderFactory.createLineBorder(Color.WHITE));
          
        // InfoPanel
        int widthOptionPanel = infosPanel.getWidth();
        infosPanel.setPreferredSize(new Dimension(widthOptionPanel, (int) (Math.round(heightFrame * 0.25))));
        infosPanel.setBackground(first);
        infosPanel.setBorder(BorderFactory.createLineBorder(Color.WHITE));
        
        //Choix du mode
        radioButtonPasPas.setBackground(first);
        radioButtonPasPas.setForeground(Color.WHITE);
        radioButtonAuto.setBackground(first);
        radioButtonAuto.setForeground(Color.WHITE);
        radioButtonPasPas.setSelected(false);
        radioButtonAuto.setSelected(true);
        
        // Choix vitesse
        jSliderVitesse.setBackground(first);
        
        //Bouton Play Pause
        ImageIcon playIcon = new ImageIcon(this.getClass().getResource("/resources/play.png"));
        jLabelPlayPause.setIcon(playIcon);
        jLabelPlayPause.setHorizontalAlignment(SwingConstants.CENTER);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionsPanel = new javax.swing.JPanel();
        radioButtonPasPas = new javax.swing.JRadioButton();
        jSliderVitesse = new javax.swing.JSlider();
        jLabel1 = new javax.swing.JLabel();
        radioButtonAuto = new javax.swing.JRadioButton();
        jLabelVitesse = new javax.swing.JLabel();
        updatePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSpinnerAddRobot = new javax.swing.JSpinner();
        jSpinneraddBoite = new javax.swing.JSpinner();
        jButtonAddRobot = new javax.swing.JButton();
        jButtonAddBoite = new javax.swing.JButton();
        jLabelNbRobots = new javax.swing.JLabel();
        jLabelNbBoites = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        infosPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabelPositionX = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabelPositionY = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabelComposantsCase = new javax.swing.JLabel();
        jLabelPlayPause = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 102));

        radioButtonPasPas.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        radioButtonPasPas.setText("Mode pas à pas");
        radioButtonPasPas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonPasPasActionPerformed(evt);
            }
        });

        jSliderVitesse.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderVitesseStateChanged(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tw Cen MT", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 152, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\WINDOWS\\Downloads\\Robot_design_64.png")); // NOI18N
        jLabel1.setText("iRobotSMA");

        radioButtonAuto.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        radioButtonAuto.setText("Mode automatique");
        radioButtonAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioButtonAutoActionPerformed(evt);
            }
        });

        jLabelVitesse.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabelVitesse.setForeground(new java.awt.Color(255, 255, 255));
        jLabelVitesse.setText("Vitesse : 100 %");

        updatePanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Gestion des composants :");

        jLabel4.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Gérer les robots");

        jLabel5.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Gérer les boites");

        jSpinnerAddRobot.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerAddRobotStateChanged(evt);
            }
        });

        jSpinneraddBoite.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinneraddBoiteStateChanged(evt);
            }
        });

        jButtonAddRobot.setText("Ajouter");
        jButtonAddRobot.setEnabled(false);
        jButtonAddRobot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddRobotActionPerformed(evt);
            }
        });

        jButtonAddBoite.setText("Ajouter");
        jButtonAddBoite.setEnabled(false);
        jButtonAddBoite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddBoiteActionPerformed(evt);
            }
        });

        jLabelNbRobots.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabelNbRobots.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNbRobots.setText("0");

        jLabelNbBoites.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabelNbBoites.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNbBoites.setText("0");

        jLabel6.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ROBOTS : ");

        jLabel7.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BOITES : ");

        javax.swing.GroupLayout updatePanelLayout = new javax.swing.GroupLayout(updatePanel);
        updatePanel.setLayout(updatePanelLayout);
        updatePanelLayout.setHorizontalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(updatePanelLayout.createSequentialGroup()
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, updatePanelLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinneraddBoite))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, updatePanelLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(jSpinnerAddRobot, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonAddRobot)
                            .addComponent(jButtonAddBoite))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(updatePanelLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelNbBoites))
                            .addGroup(updatePanelLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelNbRobots)))))
                .addGap(42, 42, 42))
        );
        updatePanelLayout.setVerticalGroup(
            updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(updatePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jSpinnerAddRobot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddRobot)
                    .addComponent(jLabelNbRobots)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(updatePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jSpinneraddBoite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAddBoite)
                    .addComponent(jLabelNbBoites)
                    .addComponent(jLabel7))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        infosPanel.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Informations de la case selectionnée :");

        jLabel8.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Position X : ");

        jLabelPositionX.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabelPositionX.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPositionX.setText("0");

        jLabel9.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Position Y : ");

        jLabelPositionY.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jLabelPositionY.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPositionY.setText("0");

        jLabel10.setFont(new java.awt.Font("Tw Cen MT", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Elements de la case : ");

        jLabelComposantsCase.setFont(new java.awt.Font("Tw Cen MT", 0, 24)); // NOI18N
        jLabelComposantsCase.setForeground(new java.awt.Color(255, 152, 0));

        javax.swing.GroupLayout infosPanelLayout = new javax.swing.GroupLayout(infosPanel);
        infosPanel.setLayout(infosPanelLayout);
        infosPanelLayout.setHorizontalGroup(
            infosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(infosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(infosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPositionX))
                    .addGroup(infosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelPositionY))
                    .addGroup(infosPanelLayout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelComposantsCase)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        infosPanelLayout.setVerticalGroup(
            infosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infosPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(29, 29, 29)
                .addGroup(infosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabelPositionX))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(infosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabelPositionY))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(infosPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabelComposantsCase))
                .addContainerGap(170, Short.MAX_VALUE))
        );

        jLabelPlayPause.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelPlayPauseMouseReleased(evt);
            }
        });

        jButton1.setText("Enregistrer grille");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Charger grille");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout optionsPanelLayout = new javax.swing.GroupLayout(optionsPanel);
        optionsPanel.setLayout(optionsPanelLayout);
        optionsPanelLayout.setHorizontalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, optionsPanelLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(infosPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updatePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSliderVitesse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, optionsPanelLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(optionsPanelLayout.createSequentialGroup()
                                        .addComponent(radioButtonAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                                        .addComponent(radioButtonPasPas, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(optionsPanelLayout.createSequentialGroup()
                                        .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelVitesse, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(optionsPanelLayout.createSequentialGroup()
                                                .addComponent(jButton1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButton2)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(optionsPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelPlayPause, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        optionsPanelLayout.setVerticalGroup(
            optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(optionsPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(4, 4, 4)
                .addGroup(optionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioButtonAuto)
                    .addComponent(radioButtonPasPas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPlayPause, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelVitesse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderVitesse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(updatePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(infosPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(357, Short.MAX_VALUE)
                .addComponent(optionsPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radioButtonAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonAutoActionPerformed
        radioButtonPasPas.setSelected(false);
        radioButtonAuto.setSelected(true);
        jSliderVitesse.setEnabled(true);
    }//GEN-LAST:event_radioButtonAutoActionPerformed

    private void radioButtonPasPasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioButtonPasPasActionPerformed
        radioButtonAuto.setSelected(false);
        radioButtonPasPas.setSelected(true);
        jSliderVitesse.setEnabled(false);
    }//GEN-LAST:event_radioButtonPasPasActionPerformed

    private void jSliderVitesseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderVitesseStateChanged
        jLabelVitesse.setText("Vitesse : " + jSliderVitesse.getValue() + " %");
    }//GEN-LAST:event_jSliderVitesseStateChanged

    private void jButtonAddRobotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddRobotActionPerformed
        int nbRobots = Integer.parseInt(jLabelNbRobots.getText());
        int nbRobotsToAdd = (int) jSpinnerAddRobot.getValue();
        nbRobots += nbRobotsToAdd;
        jLabelNbRobots.setText(String.valueOf(nbRobots));
    }//GEN-LAST:event_jButtonAddRobotActionPerformed

    private void jButtonAddBoiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddBoiteActionPerformed
        int nbBoites = Integer.parseInt(jLabelNbBoites.getText());
        int nbBoitesToAdd = (int) jSpinneraddBoite.getValue();
        nbBoites += nbBoitesToAdd;
        jLabelNbBoites.setText(String.valueOf(nbBoites));
    }//GEN-LAST:event_jButtonAddBoiteActionPerformed

    private void jSpinnerAddRobotStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerAddRobotStateChanged
        int value = (int) jSpinnerAddRobot.getValue();
        if (value == 0) {
            jButtonAddRobot.setEnabled(false);
        } else if (value < 0) {
            jButtonAddRobot.setEnabled(true);
            jButtonAddRobot.setText("Supprimer");
        } else {
            jButtonAddRobot.setEnabled(true);
            jButtonAddRobot.setText("Ajouter");
        }
    }//GEN-LAST:event_jSpinnerAddRobotStateChanged

    private void jSpinneraddBoiteStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinneraddBoiteStateChanged
        int value = (int) jSpinneraddBoite.getValue();
        if (value == 0) {
            jButtonAddBoite.setEnabled(false);
        } else if (value < 0) {
            jButtonAddBoite.setEnabled(true);
            jButtonAddBoite.setText("Supprimer");
        } else {
            jButtonAddBoite.setEnabled(true);
            jButtonAddBoite.setText("Ajouter");
        }
    }//GEN-LAST:event_jSpinneraddBoiteStateChanged

    private void jLabelPlayPauseMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelPlayPauseMouseReleased
        if (isRunning) {
            isRunning = false;
            ImageIcon playIcon = new ImageIcon(this.getClass().getResource("/resources/play.png"));
            jLabelPlayPause.setIcon(playIcon);
        } else {
            isRunning = true;
            ImageIcon pauseIcon = new ImageIcon(this.getClass().getResource("/resources/pause.png"));
            jLabelPlayPause.setIcon(pauseIcon);
        }
    }//GEN-LAST:event_jLabelPlayPauseMouseReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        persister.saveGrilleInXmlFile();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            persister.loadGrilleFromXml();
        } catch (ParserConfigurationException ex) {
            Logger.getLogger(mainFraime.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SAXException ex) {
            Logger.getLogger(mainFraime.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(mainFraime.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public JLabel getjLabelPositionX() {
        return jLabelPositionX;
    }

    public JLabel getjLabelPositionY() {
        return jLabelPositionY;
    }

    public JLabel getjLabelComposantsCase() {
        return jLabelComposantsCase;
    }

    public Grille getGrille() {
        return grille;
    }

    public JSlider getjSliderVitesse() {
        return jSliderVitesse;
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFraime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFraime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFraime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFraime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainFraime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel infosPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAddBoite;
    private javax.swing.JButton jButtonAddRobot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelComposantsCase;
    private javax.swing.JLabel jLabelNbBoites;
    private javax.swing.JLabel jLabelNbRobots;
    private javax.swing.JLabel jLabelPlayPause;
    private javax.swing.JLabel jLabelPositionX;
    private javax.swing.JLabel jLabelPositionY;
    private javax.swing.JLabel jLabelVitesse;
    private javax.swing.JSlider jSliderVitesse;
    private javax.swing.JSpinner jSpinnerAddRobot;
    private javax.swing.JSpinner jSpinneraddBoite;
    private javax.swing.JPanel optionsPanel;
    private javax.swing.JRadioButton radioButtonAuto;
    private javax.swing.JRadioButton radioButtonPasPas;
    private javax.swing.JPanel updatePanel;
    // End of variables declaration//GEN-END:variables
}
